name: authz-service

services:
  authz-service:
    image: ${AUTHZ_SERVICE_IMAGE:-authz-service:dev}
    networks:
      - service-shared

networks:
  service-shared:
    external: true
    name: ${SERVICE_SHARED_NETWORK:-${BACKEND_SHARED_NETWORK:-${MSA_SHARED_NETWORK:-service-backbone-shared}}}
