name: authz-service

services:
  authz-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      secrets:
        - gh_token
        - github_actor
    networks:
      - service-shared

secrets:
  gh_token:
    environment: GH_TOKEN
  github_actor:
    environment: GITHUB_ACTOR

networks:
  service-shared:
    external: true
    name: ${SERVICE_SHARED_NETWORK:-${BACKEND_SHARED_NETWORK:-${MSA_SHARED_NETWORK:-service-backbone-shared}}}
